os: 'linux'
dist: 'xenial'
language: 'php'
php:
  - '7.2'
  - '7.3'
  - '7.4'

before_install:
  # turn off XDebug
  - phpenv config-rm xdebug.ini || return

install:
  - composer install

script:
  - composer test

jobs:
  include:
    - stage: test
      name: PHPSTAN
      script: composer phpstan
    -
      name: Rector
      script: composer rector -- --dry-run --no-progress-bar
    -
      name: CS Fixer
      script: vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --using-cache=no --allow-risky=yes --show-progress=dots --diff $(git diff -- '*.php' --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT_RANGE}")
